apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-be9a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-be9a"
  template:
    metadata:
      labels:
        app: "akscluster-be9a"
    spec:
      containers:
        - name: "akscluster-be9a"
          image: "aksclustor.azurecr.io/akscluster"
          ports:
          - containerPort: 80